# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowInfo(object):
    def setupUi(self, MainWindowInfo):
        MainWindowInfo.setObjectName("MainWindowInfo")
        MainWindowInfo.resize(1200, 1000)
        MainWindowInfo.setMinimumSize(QtCore.QSize(1200, 1000))
        MainWindowInfo.setMaximumSize(QtCore.QSize(1200, 1000))
        MainWindowInfo.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/info or.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindowInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 150, 511, 181))
        self.textBrowser.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/pink info.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 450, 231, 91))
        self.pushButton.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/grey info.png);\n"
"font: 87 14pt \"Segoe UI Black\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ad/project pqt5/materials for the proj/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        MainWindowInfo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowInfo)
        self.statusbar.setObjectName("statusbar")
        MainWindowInfo.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowInfo)
        QtCore.QMetaObject.connectSlotsByName(MainWindowInfo)

    def retranslateUi(self, MainWindowInfo):
        _translate = QtCore.QCoreApplication.translate
        MainWindowInfo.setWindowTitle(_translate("MainWindowInfo", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindowInfo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Добрый день, вечер или утро! Я рад сообщить, что это проект для ЯЛицея по PyQT5 и Вы сейчас в маленьком описании данного проекта. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">На это приложение я потратил много времени и буду рад, если Вы оцените его по заслугам, ведь оно способно помочь Вам с вашей, видимо, финансовой проблемкой :)</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindowInfo", " ОБРАТНО"))

