# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowStart(object):
    def setupUi(self, MainWindowStart):
        MainWindowStart.setObjectName("MainWindowStart")
        MainWindowStart.resize(1200, 1000)
        MainWindowStart.setMinimumSize(QtCore.QSize(1200, 1000))
        MainWindowStart.setMaximumSize(QtCore.QSize(1200, 1000))
        MainWindowStart.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/startluna.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindowStart)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 680, 351, 61))
        self.pushButton.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/grey start.png);\n"
"font: 36pt \"MS Shell Dlg 2\";")
        self.pushButton.setText("  GO MAIN")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ad/project pqt5/materials for the proj/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(52, 64))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 531, 121))
        self.label.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/pink start.png);\n"
"font: 75 72pt \"Segoe Print\";")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 780, 351, 61))
        self.pushButton_2.setStyleSheet("background-image: url(:/ad/project pqt5/materials for the proj/grey start.png);\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton_2.setText(" INFORM")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ad/project pqt5/materials for the proj/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(52, 64))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindowStart.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowStart)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindowStart.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowStart)
        self.statusbar.setObjectName("statusbar")
        MainWindowStart.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowStart)
        QtCore.QMetaObject.connectSlotsByName(MainWindowStart)

    def retranslateUi(self, MainWindowStart):
        _translate = QtCore.QCoreApplication.translate
        MainWindowStart.setWindowTitle(_translate("MainWindowStart", "MainWindow"))
        self.label.setText(_translate("MainWindowStart", "CachCheck"))

